import type { Metadata } from "next";
import { profile } from "@/data/profile";
import { siteName } from "@/lib/site";

/**
 * Site-wide social preview image (generated by app/opengraph-image.tsx). Pages that define their
 * own `openGraph` replace the inherited image, so it is attached explicitly here.
 */
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${profile.fullName} — ${profile.jobTitle}, ${profile.department}, ${profile.institution}`,
};

/** Per-page metadata with canonical URL and matching Open Graph / Twitter tags. */
export function pageMetadata({
  title,
  description,
  path,
  type = "website",
}: {
  title: string;
  description: string;
  path: string;
  type?: "website" | "article" | "profile";
}): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      siteName,
      title: `${title} | ${profile.fullName}`,
      description,
      url: path,
      locale: "en_IN",
      images: [shareImage],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${profile.fullName}`,
      description,
      images: [shareImage.url],
    },
  };
}
